### ISSUE TITLE
[Question] Can be used in android project?

### ISSUE THREAD

**Issue by le4ker** [m9aertner/PBKDF2#4]
Hey!

Thanks for sharing.

I have a android project in Android Studio that is set up with gradle and maven, will I be able to use your library?

Thanks!
:panos

**Comment by m9aertner** [comment]
Hello Panos,

it's been a while since I did my last Android programming, but, **yes**, I think it should be possible to use this JAR file with Android.

I made sure to compile the JAR with Java 6 (major version: 50, minor version: 0), so the stock dependency (Gradle 'de.rtner:PBKDF2:1.1.1') will load a Jar that has no bytecode that Dalvik doesn't understand.

The other requirement is that the underlying algorithm "HMacSHA1" needs to be supported by Android. I would bet it is, but currently I have no environment to actually test this, unfortunately.

I'd appreciate it if you could update us on any findings you have on this.

Thanks,
Matthias
